version: '2.1'

services:

  go:
    build: ../
    container_name: go
    hostname: go
    depends_on: 
      - selenium-hub
    ports:
      - 5000:5000
    expose:
      - 5000
    environment:
      - INTERVAL_IN_HOURS=24

  selenium-hub:
    image: selenium/hub:3.14.0-gallium
    # image: deinchristian/rpi-selenium-hub
    container_name: selenium-hub
    hostname: selenium-hub
    expose:
      - 4444
    ports:
      - 4444:4444

  selenium-chrome:
    image: selenium/node-chrome:3.14.0-gallium
    # image: deinchristian/rpi-selenium-node-chrome
    hostname: selenium-chrome
    depends_on: 
      - selenium-hub
    ports:
      - "5900:5900"
    shm_size: 128M
    depends_on:
      - selenium-hub
    environment:
    - HUB_PORT_4444_TCP_ADDR=selenium-hub
    - HUB_PORT_4444_TCP_PORT=4444
    - HUB_HOST=selenium-hub

  postgres:
    build: ./postgres
    container_name: postgres
    hostname: postgres
    environment:
      # First 4 variables used to configure DB
      - POSTGRES_USER=shiny_user
      - POSTGRES_PASSWORD=shroot
      - POSTGRES_DB=shiny_db
      - POSTGRES_PORT=5432
      # Next 3 variables needed to avoid "FATAL role 'root' does not exist" error
      - PGDATABASE=shiny_db
      - PGUSER=shiny_user
      - PGPASSWORD=shroot
    ports:
      - 5432:5432
    expose:
      - 5432
    restart: always
    healthcheck:
      test: pg_isready --host localhost || exit 1
      interval: 15s
      timeout: 10s
      retries: 30